[project]
name = "ansible-collection-caktus-hosting-services"
version = "0.1.0"
description = "A collection of useful Ansible roles for managing virtual and physical servers"
requires-python = ">=3.10"
dependencies = ["pyyaml>=6.0.3", "requests>=2.34.2"]

# Tell uv NOT to attempt building or installing the root directory as a wheel
[tool.uv]
package = false

[dependency-groups]
dev = [
    "ansible>=10.7.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "requests-mock>=1.12.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
