- name: Configure uptime tests
  tags: uptime
  caktus.hosting_services.statuscake_uptime_test:
    api_key: "{{ statuscake_api_key }}"
    name: "{{ item['name'] }}"
    website_url: "{{ item['website_url'] }}"
    basic_username: "{{ item['basic_username']|default(statuscake_basic_username) }}"
    basic_password: "{{ item['basic_password']|default(statuscake_basic_password) }}"
    check_rate: "{{ item['check_rate']|default(statuscake_check_rate) }}"
    contact_groups: "{{ item['contact_groups'] | default(statuscake_contact_groups) }}"
    final_endpoint: "{{ item['final_endpoint']|default(statuscake_final_endpoint) }}"
    follow_redirects: "{{ item['follow_redirects']|default(statuscake_follow_redirects) }}"
    log_file: "{{ item['log_file']|default(statuscake_log_file) }}"
    find_string: "{{ item['find_string']|default(statuscake_find_string) }}"
    confirmation: "{{ item['confirmation']|default(statuscake_confirmation) }}"
    custom_header: "{{ item['custom_header']|default(statuscake_custom_header) }}"
    do_not_find: "{{ item['do_not_find']|default(statuscake_do_not_find) }}"
    dns_ip: "{{ item['dns_ip']|default(statuscake_dns_ip) }}"
    dns_server: "{{ item['dns_server']|default(statuscake_dns_server) }}"
    enable_ssl_alert: "{{ item['enable_ssl_alert']|default(statuscake_enable_ssl_alert) }}"
    host: "{{ item['host']|default(statuscake_host) }}"
    include_header: "{{ item['include_header']|default(statuscake_include_header) }}"
    paused: "{{ item['paused']|default(statuscake_paused) }}"
    port: "{{ item['port']|default(statuscake_port)|default(omit,true) }}"
    post_body: "{{ item['post_body']|default(statuscake_post_body) }}"
    post_raw: "{{ item['post_raw']|default(statuscake_post_raw) }}"
    regions: "{{ item['regions']|default(statuscake_regions) }}"
    state: "{{ item['state'] | default(statuscake_state) }}"
    status_codes: "{{ item['status_codes']|default(statuscake_status_codes)|default(omit,true) }}"
    tags: "{{ item['tags'] | default(statuscake_tags) | default(statuscake_) }}"
    test_type: "{{ item['test_type']|default(statuscake_test_type) }}"
    timeout: "{{ item['timeout']|default(statuscake_timeout)|default(omit,true) }}"
    trigger_rate: "{{ item['trigger_rate']|default(statuscake_trigger_rate)|default(omit,true) }}"
    use_jar: "{{ item['use_jar']|default(statuscake_use_jar) }}"
    user_agent: "{{ item['user_agent']|default(statuscake_user_agent) }}"
  when: "'uptime' in item['test_types'] | default(statuscake_test_types)"
  loop: "{{ statuscake_tests }}"
  loop_control:
    label: "{{ item['website_url'] }}"

- name: Configure ssl tests
  tags: ssl
  caktus.hosting_services.statuscake_ssl_test:
    api_key: "{{ statuscake_api_key }}"
    state: "{{ item['state'] | default(statuscake_ssl_state) }}"
    website_url: "{{ item['website_url'] }}"
    check_rate: "{{ item['check_rate']|default(statuscake_ssl_check_rate) }}"
    contact_groups: "{{ item['contact_groups']|default(statuscake_ssl_contact_groups) }}"
    alert_at: "{{ item['alert_at']|default(statuscake_ssl_alert_at) }}"
    alert_reminder: "{{ item['alert_reminder']|default(statuscake_ssl_alert_reminder) }}"
    alert_expiry: "{{ item['alert_expiry']|default(statuscake_ssl_alert_expiry) }}"
    alert_broken: "{{ item['alert_broken']|default(statuscake_ssl_alert_broken) }}"
    alert_mixed: "{{ item['alert_mixed']|default(statuscake_ssl_alert_mixed) }}"
    follow_redirects: "{{ item['follow_redirects']|default(statuscake_ssl_follow_redirects) }}"
    paused: "{{ item['paused']|default(statuscake_ssl_paused) }}"
    hostname: "{{ item['hostname']|default(statuscake_ssl_hostname) }}"
    user_agent: "{{ item['user_agent']|default(statuscake_ssl_user_agent) }}"
    log_file: "{{ item['log_file']|default(statuscake_ssl_log_file) }}"
  when: "'ssl' in item['test_types'] | default(statuscake_test_types)"
  loop: "{{ statuscake_tests }}"
  loop_control:
    label: "{{ item['website_url'] }}"
