- name: Merge statuscake_uptime_tests with templates
  set_fact:
    merged_statuscake_uptime_tests: "{{ (merged_statuscake_uptime_tests | default([])) + [ item['template'] | default([]) | combine(item) ] }}"
  loop: "{{ statuscake_uptime_tests }}"
  loop_control:
    label: "{{ item['name'] }}"

- name: Configure uptime tests
  caktus.hosting_services.statuscake_uptime_test:
    api_key: "{{ statuscake_api_key }}"
    state: "{{ item['state'] }}"
    name: "{{ item['name'] }}"
    check_rate: "{{ item['check_rate']|default(statuscake_default_check_rate) }}"
    test_type: "{{ item['test_type']|default(statuscake_default_test_type) }}"
    website_url: "{{ item['website_url'] }}"
    basic_user: "{{ item['basic_user']|default(omit) }}"
    basic_pass: "{{ item['basic_pass']|default(omit) }}"
    tags: "{{ item['tags']|default(omit) }}"
    contact_groups: "{{ item['contact_groups']|default(omit) }}"
    final_endpoint: "{{ item['final_endpoint']|default(omit) }}"
    follow_redirects: "{{ item['follow_redirects']|default(omit) }}"
    log_file: "{{ item['log_file']|default(omit) }}"
  loop: "{{ merged_statuscake_uptime_tests }}"
  loop_control:
    label: "{{ item['name'] }}"

- name: Clean up variables
  set_fact:
    merged_statuscake_uptime_tests: []
